const projectData = [
  { id: 'website', name: 'Website Redesign', desc: 'Refresh the marketing site with a clearer story and updated visual system.', status: 'In progress', color: 'blue', progress: 68, tasks: 12, due: 'Oct 24', members: ['JD','MP','SK'] },
  { id: 'mobile', name: 'Mobile App v2', desc: 'Improve the mobile experience and prepare the next release.', status: 'In progress', color: 'amber', progress: 42, tasks: 18, due: 'Nov 08', members: ['MP','AL','JD'] },
  { id: 'onboarding', name: 'Customer Onboarding', desc: 'Make the first week easier for every new customer.', status: 'Planning', color: '', progress: 18, tasks: 8, due: 'Nov 15', members: ['SK','AL'] },
  { id: 'brand', name: 'Brand Guidelines', desc: 'Document the visual language and shared design resources.', status: 'Completed', color: 'green', progress: 100, tasks: 9, due: 'Oct 10', members: ['JD','SK'] },
  { id: 'analytics', name: 'Analytics Dashboard', desc: 'Bring key product signals into one useful workspace.', status: 'In progress', color: 'blue', progress: 55, tasks: 14, due: 'Nov 22', members: ['AL','MP'] }
];
const taskData = [
  { name: 'Review homepage wireframes', project: 'Website Redesign', status: 'In progress', priority: 'High', due: 'Today', assignee: 'JD' },
  { name: 'Prepare user interview guide', project: 'Customer Onboarding', status: 'To do', priority: 'Medium', due: 'Today', assignee: 'MP' },
  { name: 'Finalize icon set', project: 'Mobile App v2', status: 'In review', priority: 'Low', due: 'Oct 18', assignee: 'SK' },
  { name: 'Share updated color tokens', project: 'Brand Guidelines', status: 'Done', priority: 'Medium', due: 'Oct 16', assignee: 'AL' },
  { name: 'Map account setup flow', project: 'Customer Onboarding', status: 'To do', priority: 'High', due: 'Oct 21', assignee: 'JD' },
  { name: 'Test dashboard empty state', project: 'Analytics Dashboard', status: 'In progress', priority: 'Medium', due: 'Oct 23', assignee: 'MP' },
  { name: 'Draft release notes', project: 'Mobile App v2', status: 'To do', priority: 'Low', due: 'Oct 26', assignee: 'SK' }
];
const routes = { home:'Home', dashboard:'Dashboard', projects:'Projects', project:'Project Details', tasks:'Tasks', task:'Task Details', assistant:'AI Assistant', profile:'Profile / Settings', login:'Login', register:'Register' };
let aiMode = 'suggestions';
const app = document.querySelector('#app');
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const go = (route, id='') => `#/${route}${id ? `/${encodeURIComponent(id)}` : ''}`;
const tag = (label, cls='') => `<span class="tag ${cls}">${esc(label)}</span>`;
const statusClass = s => ({'Done':'green','Completed':'green','In progress':'blue','In review':'amber','To do':'','Planning':''}[s] || '');
const priorityClass = s => ({High:'rose',Medium:'amber',Low:''}[s] || '');
const avatar = (s, cls='') => `<span class="avatar ${cls}">${esc(s)}</span>`;
function sidebar(route) {
  const links = [['dashboard','▦','Overview'],['projects','▣','Projects'],['tasks','☷','My tasks'],['assistant','✳','AI Assistant']];
  return `<aside class="sidebar" id="sidebar"><a class="brand" href="${go('home')}"><span class="brand-mark">t</span>taskflow</a><div class="workspace"><span class="workspace-icon">N</span><span class="workspace-name">Northstar Studio<span class="workspace-caption">Free workspace</span></span><span>⌄</span></div><div class="nav-label">Workspace</div><nav class="nav-list">${links.map(([r,i,n])=>`<a class="nav-link ${route===r||route==='project'&&r==='projects'||route==='task'&&r==='tasks'?'active':''}" href="${go(r)}"><span class="nav-icon">${i}</span>${n}${r==='tasks'?'<span class="nav-count">7</span>':''}</a>`).join('')}</nav><div class="nav-label">Personal</div><nav class="nav-list"><a class="nav-link ${route==='profile'?'active':''}" href="${go('profile')}"><span class="nav-icon">⚙</span>Settings</a></nav><div class="sidebar-bottom"><div class="upgrade-card"><strong>Make space for good work</strong><p>Keep your projects and priorities moving forward.</p><a href="${go('projects')}">Explore your workspace →</a></div><a class="user-chip" href="${go('profile')}">${avatar('JD')}<span><span class="user-name">Jordan Davis</span><span class="user-email">jordan@northstar.co</span></span><span style="margin-left:auto;color:#89909a">···</span></a></div></aside>`;
}
function frame(route, body) { return `<div class="shell">${sidebar(route)}<main class="main"><header class="topbar"><div class="breadcrumb-wrap"><button class="mobile-menu" aria-label="Open navigation" onclick="toggleSidebar()">☰</button><div class="breadcrumb">Workspace <span style="padding:0 6px;color:#c2c6ce">/</span> <strong>${routes[route]||'TaskFlow'}</strong></div></div><div class="top-actions"><button class="icon-button" aria-label="Notifications">♧</button><a class="top-avatar" href="${go('profile')}">JD</a></div></header><section class="content">${body}</section></main></div>`; }
function pageHead(title, sub, action='') { return `<div class="page-head"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${action}</div>`; }
function projectCard(p) { return `<article class="card project-card" data-search="${esc((p.name+' '+p.desc+' '+p.status).toLowerCase())}"><div class="project-card-head"><span class="project-symbol">${p.name.slice(0,1)}</span>${tag(p.status,statusClass(p.status))}</div><a href="${go('project',p.id)}"><h3>${esc(p.name)}</h3></a><p>${esc(p.desc)}</p><div class="progress-label"><span>Progress</span><strong>${p.progress}%</strong></div><div class="progress"><span style="width:${p.progress}%"></span></div><div class="card-foot"><span>☷ ${p.tasks} tasks · Due ${p.due}</span><span class="avatars">${p.members.map((m,i)=>avatar(m,['','purple','teal'][i%3])).join('')}</span></div></article>`; }
function taskRows(items) { return `<div class="task-list">${items.map((t,i)=>`<div class="task-row"><span class="check" aria-hidden="true"></span><a href="${go('task',String(i))}"><span class="task-name">${esc(t.name)}</span><span class="task-sub">${esc(t.project)} · ${esc(t.due)}</span></a>${tag(t.status,statusClass(t.status))}</div>`).join('')}</div>`; }
function dashboard() { const tasks=taskData.slice(0,4); return `${pageHead('Good morning, Jordan 👋','Here’s what’s happening across your workspace.',`<a class="button primary" href="${go('projects')}">＋ New project</a>`)}<div class="grid stats">${[['Active projects','5','2 due this month','▣'],['Tasks completed','24','↑ 12% this week','✓'],['Tasks in progress','8','Across 4 projects','◷'],['Due this week','6','2 due today','⌁']].map(([l,v,n,i])=>`<article class="card stat-card"><div class="stat-top">${l}<span class="stat-icon">${i}</span></div><div class="stat-value">${v}</div><div class="stat-note"><span class="${n.includes('↑')?'positive':''}">${n}</span></div></article>`).join('')}</div><div class="grid overview-grid"><section class="card panel"><div class="panel-heading"><h2>Active projects</h2><a class="text-link" href="${go('projects')}">View all →</a></div><div class="project-list">${projectData.slice(0,3).map(p=>`<a class="project-row" href="${go('project',p.id)}"><div><div class="project-title">${esc(p.name)}</div><div class="project-meta">${p.tasks} tasks · Due ${p.due}</div></div>${tag(p.status,statusClass(p.status))}<div class="project-progress"><div class="progress-label"><span>Progress</span><strong>${p.progress}%</strong></div><div class="progress"><span style="width:${p.progress}%"></span></div></div></a>`).join('')}</div></section><section class="card panel"><div class="panel-heading"><h2>My tasks</h2><a class="text-link" href="${go('tasks')}">View all →</a></div>${taskRows(tasks)}</section></div>`; }
function projects() { return `${pageHead('Projects','Plan together and keep every initiative moving.',`<button class="button primary" onclick="openModal('project')">＋ New project</button>`)}<div class="toolbar"><input class="search" id="project-search" placeholder="⌕  Search projects" aria-label="Search projects"><select class="select" id="project-filter" aria-label="Filter projects"><option value="all">All statuses</option><option>In progress</option><option>Planning</option><option>Completed</option></select></div><div class="grid project-cards" id="project-grid">${projectData.map(projectCard).join('')}</div>`; }
function projectDetail(id) { const p=projectData.find(x=>x.id===id)||projectData[0], related=taskData.filter(t=>t.project===p.name); return `${pageHead(`<span class="detail-title"><span class="project-symbol">${p.name.slice(0,1)}</span>${esc(p.name)}</span>`,`Project · Updated recently`,`<button class="button" onclick="openModal('project')">Edit project</button>`)}<div class="grid detail-layout"><section class="card panel"><div class="detail-section"><h2>About this project</h2><p class="detail-copy">${esc(p.desc)} The team is collaborating to deliver thoughtful, high-quality work on schedule.</p></div><div class="detail-section"><div class="panel-heading"><h2>Tasks</h2><button class="button primary" onclick="openModal('task')">＋ Add task</button></div>${related.length?`<div class="table-wrap"><table><thead><tr><th>Task</th><th>Assignee</th><th>Priority</th><th>Status</th></tr></thead><tbody>${related.map(t=>`<tr><td><a class="task-table-title" href="${go('task',taskData.indexOf(t))}">${esc(t.name)}</a></td><td>${esc(t.assignee)}</td><td>${tag(t.priority,priorityClass(t.priority))}</td><td>${tag(t.status,statusClass(t.status))}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No tasks in this project yet.</div>'}</div><div class="detail-section"><h2>Updates</h2><p class="detail-copy">Jordan updated the project plan · Yesterday</p></div></section><aside class="card panel"><div class="detail-section"><h2>Project details</h2><div class="info-list"><div class="info-line"><span>Status</span><strong>${tag(p.status,statusClass(p.status))}</strong></div><div class="info-line"><span>Progress</span><strong>${p.progress}%</strong></div><div class="info-line"><span>Due date</span><strong>${p.due}, 2026</strong></div><div class="info-line"><span>Tasks</span><strong>${p.tasks} total</strong></div></div><div style="margin-top:14px" class="progress"><span style="width:${p.progress}%"></span></div></div><div class="detail-section"><h2>Project members</h2>${p.members.map((m,i)=>`<div class="member-line">${avatar(m,['','purple','teal'][i%3])}<span>${({JD:'Jordan Davis',MP:'Morgan Patel',SK:'Sam Kim',AL:'Alex Lee'})[m]}</span></div>`).join('')}</div></aside></div>`; }
function tasks() { return `${pageHead('My tasks','A focused view of the work on your plate.',`<button class="button primary" onclick="openModal('task')">＋ New task</button>`)}<div class="toolbar"><input class="search" id="task-search" placeholder="⌕  Search tasks" aria-label="Search tasks"><select class="select" id="task-filter" aria-label="Filter tasks"><option value="all">All statuses</option><option>To do</option><option>In progress</option><option>In review</option><option>Done</option></select><select class="select" aria-label="Filter priority"><option>All priorities</option><option>High</option><option>Medium</option><option>Low</option></select></div><section class="card panel table-wrap"><table id="task-table"><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Priority</th><th>Status</th><th>Due date</th></tr></thead><tbody>${taskData.map((t,i)=>`<tr data-search="${esc((t.name+' '+t.project+' '+t.status+' '+t.priority).toLowerCase())}" data-status="${t.status}"><td><a class="task-table-title" href="${go('task',i)}">${esc(t.name)}</a></td><td>${esc(t.project)}</td><td>${avatar(t.assignee)}</td><td>${tag(t.priority,priorityClass(t.priority))}</td><td>${tag(t.status,statusClass(t.status))}</td><td>${t.due}</td></tr>`).join('')}</tbody></table></section>`; }
function taskDetail(id) { const t=taskData[Number(id)]||taskData[0]; return `${pageHead('Task details',`From ${esc(t.project)}`,`<button class="button" onclick="openModal('task')">Edit task</button>`)}<div class="grid detail-layout"><section class="card panel"><div class="detail-section"><div class="detail-title"><span class="check"></span><h1>${esc(t.name)}</h1></div><p class="detail-copy" style="margin-top:14px">Complete this task and share an update with your project team. Add any context or links that will help reviewers.</p></div><div class="detail-section"><h2>Description</h2><p class="detail-copy">Review the latest project materials, capture any changes, and make sure the team is aligned before moving this work forward.</p></div><div class="detail-section"><h2>Activity</h2><p class="detail-copy">Jordan created this task · Oct 14, 2026</p></div></section><aside class="card panel"><div class="detail-section"><h2>Task properties</h2><div class="info-list"><div class="info-line"><span>Status</span><strong>${tag(t.status,statusClass(t.status))}</strong></div><div class="info-line"><span>Priority</span><strong>${tag(t.priority,priorityClass(t.priority))}</strong></div><div class="info-line"><span>Assignee</span><strong>${avatar(t.assignee)}</strong></div><div class="info-line"><span>Due date</span><strong>${t.due}, 2026</strong></div><div class="info-line"><span>Project</span><strong>${esc(t.project)}</strong></div></div></div></aside></div>`; }
function assistant() { const breakdown=aiMode==='breakdown'; return `${pageHead('AI Assistant','A planning companion for your projects.', '')}<div class="grid ai-layout"><aside class="card ai-tabs"><h3>Tools</h3><button class="ai-tab ${!breakdown?'active':''}" onclick="setAiMode('suggestions')">✳ <span>Task Suggestions</span></button><button class="ai-tab ${breakdown?'active':''}" onclick="setAiMode('breakdown')">☷ <span>Task Breakdown</span></button></aside><section class="card ai-chat"><div class="ai-chat-head"><strong>${breakdown?'AI Task Breakdown':'AI Task Suggestions'}</strong><span>Planning assistant · UI preview</span></div><div class="notice">This is a UI preview. AI responses are sample content; no AI service is connected.</div><div class="ai-messages" id="ai-messages"><div class="message"><p>${breakdown?'Share a larger task and I can help outline smaller steps.':'Tell me about your project goal and I can suggest a few tasks to get started.'}</p></div>${breakdown?'<div class="message"><p><strong>Example breakdown</strong></p><ol><li>Gather requirements and references</li><li>Draft the first version</li><li>Review with project members</li><li>Apply feedback and share for approval</li></ol></div>':''}</div><form class="ai-input" id="ai-form"><input id="ai-prompt" placeholder="${breakdown?'Describe a task to break down…':'Describe your project goal…'}" aria-label="Message AI assistant"><button class="button primary">Send</button></form></section></div>`; }
function profile() { return `${pageHead('Profile & settings','Manage your personal details and preferences.','')}<div class="grid detail-layout"><section class="card panel"><div class="panel-heading"><h2>Personal information</h2></div><form id="profile-form" class="form-grid"><div class="field"><label for="full-name">Full name</label><input id="full-name" value="Jordan Davis"></div><div class="field"><label for="profile-email">Email address</label><input id="profile-email" type="email" value="jordan@northstar.co"></div><div class="field"><label for="job-title">Job title</label><input id="job-title" value="Product Designer"></div><div class="field"><label for="timezone">Timezone</label><select id="timezone"><option>Pacific Time (UTC−08:00)</option><option>India Standard Time (UTC+05:30)</option></select></div><div class="field full"><label for="bio">About</label><textarea id="bio">Designing useful experiences with a thoughtful team.</textarea></div><div class="field full"><button class="button primary" style="justify-self:start">Save changes</button></div></form></section><aside class="card panel"><div class="detail-section"><h2>Workspace</h2><div class="info-list"><div class="info-line"><span>Name</span><strong>Northstar Studio</strong></div><div class="info-line"><span>Members</span><strong>8 people</strong></div><div class="info-line"><span>Plan</span><strong>Free</strong></div></div></div><div class="detail-section"><h2>Notifications</h2><div class="field"><label><input type="checkbox" checked> Task assignment updates</label><label><input type="checkbox" checked> Project activity digest</label></div></div></aside></div>`; }
function landing() { return `<div class="landing"><nav class="landing-nav"><a class="brand" href="${go('home')}"><span class="brand-mark">t</span>taskflow</a><div class="landing-links"><a href="#features">Features</a><a href="${go('login')}">Log in</a><a class="button primary" href="${go('register')}">Get started</a></div></nav><section class="landing-hero"><div class="eyebrow">A clearer way to work together</div><h1>Good work happens when work flows.</h1><p>Bring projects, tasks, and your team into one calm, focused workspace. Plan clearly, move confidently, and make room for the work that matters.</p><div class="landing-actions"><a class="button primary" href="${go('register')}">Get started for free →</a><a class="button" href="${go('login')}">Sign in</a></div></section><div class="landing-preview"><div class="preview-bar"><i class="preview-dot"></i><i class="preview-dot"></i><i class="preview-dot"></i></div><div class="preview-grid">${[1,2,3].map((_,i)=>`<div class="preview-card"><div class="preview-line short" style="background:${i===0?'#e9eaff':'#eceef3'}"></div><div class="preview-line"></div><div class="preview-line short"></div><div style="margin-top:22px" class="progress"><span style="width:${[68,42,82][i]}%"></span></div><div class="preview-line short" style="margin-top:15px"></div></div>`).join('')}</div></div><section class="landing-features" id="features"><div class="eyebrow">Everything in sync</div><h2>Make progress feel simple</h2><div class="grid feature-grid">${[['▣','Projects with purpose','Keep goals, people, and progress together.'],['☷','Tasks with context','Make ownership and next steps easy to see.'],['✳','AI planning support','Explore task ideas and practical breakdowns.']].map(([i,h,p])=>`<article class="feature-card"><span class="stat-icon">${i}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section></div>`; }
function auth(register=false) { return `<div class="auth-page"><aside class="auth-aside"><a class="brand" href="${go('home')}"><span class="brand-mark">t</span>taskflow</a><div class="auth-quote"><blockquote>“A little more clarity makes room for a lot more good work.”</blockquote><p>Plan, collaborate, and move forward together.</p></div><p class="subtitle">TaskFlow · Make work flow</p></aside><main class="auth-main"><form class="auth-form" id="auth-form"><h1>${register?'Create your account':'Welcome back'}</h1><p>${register?'Start organizing your work with TaskFlow.':'Sign in to continue to your workspace.'}</p>${register?'<div class="field"><label for="auth-name">Full name</label><input id="auth-name" autocomplete="name" placeholder="Your name" required></div>':''}<div class="field"><label for="auth-email">Email address</label><input id="auth-email" type="email" autocomplete="email" placeholder="you@company.com" required></div><div class="field"><label for="auth-password">Password</label><input id="auth-password" type="password" autocomplete="${register?'new-password':'current-password'}" placeholder="${register?'At least 8 characters':'Enter your password'}" required minlength="8"></div>${register?'<label class="subtitle" style="display:flex;align-items:center;gap:7px;margin:2px 0 12px"><input type="checkbox" required> I agree to the terms and privacy policy</label>':'<div style="text-align:right;margin:0 0 12px"><a class="text-link" href="#" onclick="event.preventDefault();toast(\'Password recovery will be available soon.\')">Forgot password?</a></div>'}<button class="button primary">${register?'Create account':'Sign in'}</button><div class="auth-switch">${register?'Already have an account?':'New to TaskFlow?'} <a href="${go(register?'login':'register')}">${register?'Sign in':'Create an account'}</a></div><div class="auth-switch">Static UI preview · no account data is sent</div></form></main></div>`; }
function render() { const parts=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean), route=parts[0]||'home', id=parts[1]||''; document.title=`${routes[route]||'TaskFlow'} · TaskFlow`; let html; switch(route){case 'dashboard':html=frame(route,dashboard());break;case 'projects':html=frame(route,projects());break;case 'project':html=frame(route,projectDetail(decodeURIComponent(id)));break;case 'tasks':html=frame(route,tasks());break;case 'task':html=frame(route,taskDetail(id));break;case 'assistant':html=frame(route,assistant());break;case 'profile':html=frame(route,profile());break;case 'login':html=auth(false);break;case 'register':html=auth(true);break;default:html=landing();} app.innerHTML=html; bindPage(); }
function bindPage() { document.querySelector('#project-search')?.addEventListener('input',filterProjects);document.querySelector('#project-filter')?.addEventListener('change',filterProjects);document.querySelector('#task-search')?.addEventListener('input',filterTasks);document.querySelector('#task-filter')?.addEventListener('change',filterTasks);document.querySelector('#ai-form')?.addEventListener('submit',sendPrompt);document.querySelector('#profile-form')?.addEventListener('submit',e=>{e.preventDefault();toast('Profile changes are preview only.');});document.querySelector('#auth-form')?.addEventListener('submit',e=>{e.preventDefault();toast('This sign-in form is a UI preview only.');}); }
function filterProjects(){const q=document.querySelector('#project-search').value.toLowerCase(), s=document.querySelector('#project-filter').value;document.querySelectorAll('#project-grid .project-card').forEach(el=>el.hidden=!(el.dataset.search.includes(q)&&(s==='all'||el.querySelector('.tag').textContent===s)));}
function filterTasks(){const q=document.querySelector('#task-search').value.toLowerCase(),s=document.querySelector('#task-filter').value;document.querySelectorAll('#task-table tbody tr').forEach(el=>el.hidden=!(el.dataset.search.includes(q)&&(s==='all'||el.dataset.status===s)));}
function toggleSidebar(){document.querySelector('#sidebar')?.classList.toggle('open');}
function setAiMode(mode){aiMode=mode;render();}
function sendPrompt(e){e.preventDefault();const input=document.querySelector('#ai-prompt'),value=input.value.trim();if(!value)return;const messages=document.querySelector('#ai-messages');messages.insertAdjacentHTML('beforeend',`<div class="message user"><p>${esc(value)}</p></div><div class="message"><p>${aiMode==='breakdown'?'Here is a sample breakdown you can adapt:' :'Here are a few sample starting points for your project:'}</p><ol>${(aiMode==='breakdown'?['Clarify the outcome and requirements','Prepare a first draft or plan','Review with the project team','Finalize and share the result']:['Align on the goal and success measures','Identify the key audience and needs','Draft an initial plan and assign owners','Set a checkpoint to review progress']).map(x=>`<li>${x}</li>`).join('')}</ol></div>`);input.value='';messages.scrollTop=messages.scrollHeight;}
function openModal(type){const project=type==='project', title=project?'Create a project':'Create a task';const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.id='modal-backdrop';overlay.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${title}</h2><button class="close-button" aria-label="Close" onclick="closeModal()">×</button></div><form id="create-form"><div class="form-grid"><div class="field full"><label for="item-title">${project?'Project name':'Task name'}</label><input id="item-title" required placeholder="${project?'e.g. Website redesign':'e.g. Review project brief'}"></div><div class="field full"><label for="item-desc">Description</label><textarea id="item-desc" placeholder="Add a little context"></textarea></div>${project?'<div class="field"><label for="item-status">Status</label><select id="item-status"><option>Planning</option><option>In progress</option></select></div>':`<div class="field"><label for="item-project">Project</label><select id="item-project">${projectData.map(p=>`<option>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label for="item-priority">Priority</label><select id="item-priority"><option>Medium</option><option>High</option><option>Low</option></select></div><div class="field"><label for="item-due">Due date</label><input id="item-due" type="date"></div><div class="field"><label for="item-assignee">Assignee</label><select id="item-assignee"><option>Jordan Davis</option><option>Morgan Patel</option><option>Sam Kim</option></select></div>`}</div><div class="form-actions"><button type="button" class="button" onclick="closeModal()">Cancel</button><button class="button primary">${project?'Create project':'Create task'}</button></div></form></section>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay)closeModal();});document.querySelector('#create-form').addEventListener('submit',e=>{e.preventDefault();closeModal();toast(`${project?'Project':'Task'} form is a UI preview only.`);});document.querySelector('#item-title').focus();}
function closeModal(){document.querySelector('#modal-backdrop')?.remove();}
function toast(text){document.querySelector('#toast')?.remove();const el=document.createElement('div');el.id='toast';el.textContent=text;el.style.cssText='position:fixed;z-index:30;bottom:22px;left:50%;transform:translateX(-50%);padding:11px 16px;background:#252b35;color:white;border-radius:8px;font-size:11px;box-shadow:0 7px 22px #151b2530';document.body.appendChild(el);setTimeout(()=>el.remove(),2600);}
window.addEventListener('hashchange',render);window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});render();
